// Generated by CoffeeScript 1.6.3
(function() {
  var adjustLayout, clearBackground, drawAlignmentGrid;

  $(document).ready(function() {
    var ctx;
    adjustLayout();
    ctx = $('#canvas')[0].getContext("2d");
    ctx.width = ctx.canvas.width;
    ctx.height = ctx.canvas.height;
    clearBackground(ctx);
    return drawAlignmentGrid(ctx);
  });

  adjustLayout = function() {
    var canvas, canvasContainer, offset, parentHeight;
    canvasContainer = $('.canvasContainer');
    parentHeight = canvasContainer.offsetParent().height();
    offset = canvasContainer.offset().top;
    canvasContainer.height(parentHeight - offset - 5);
    canvas = $('#canvas');
    canvas[0].width = canvasContainer.width();
    return canvas[0].height = canvasContainer.height();
  };

  clearBackground = function(ctx) {
    ctx.fillStyle = '#000';
    return ctx.fillRect(0, 0, ctx.width, ctx.height);
  };

  drawAlignmentGrid = function(ctx) {
    ctx.beginPath();
    ctx.setStrokeColor('#333');
    ctx.arc(ctx.width / 2, ctx.height / 2, 10, 0, Math.PI * 2, false);
    ctx.moveTo(ctx.width / 2, 0);
    ctx.lineTo(ctx.width / 2, ctx.height);
    ctx.moveTo(0, ctx.height / 2);
    ctx.lineTo(ctx.width, ctx.height / 2);
    return ctx.stroke();
  };

}).call(this);
